### ISSUE TITLE
Endless simulation parameter is ignored

### ISSUE THREAD

**Issue by LordTy** [controllab/fmi-export-20sim#18]
When the endless simulation is set (Run Properties > More > Endless) and a FMI model is exported.
The model still stops simulation after the finish time. 
While one would expect the model to continue indefinitely.

This happens on version 4.6.1 (build 6898)

**Comment by margro** [comment]
The endless setting there is not exported during code generation to an FMU. I've added a feature request for this to our bug tracker.

According to the standard, the co-simulation engine should be able to request an endless simulation using the 'stopTimeDefined argument of the fmi2SetupExperiment() function.
The template in 20-sim 4.6.1 does not yet react on this boolean. This is already fixed in the master branch of this repository and will be fixed in 20-sim 4.6.2 too.

**Comment by margro** [comment]
I'm closing this issue here since the endless simulation part in the exported FMU should work fine now in 20-sim 4.6.2 and above. For an FMU, you will need to use the _stopTimeDefined_ argument from the fmi2SetupExperiment() function.

Note that the feature request for exporting the 20-sim setting is still open in our bug tracker.
