### ISSUE TITLE
unresolved external symbol xx_stop_simulation

### ISSUE THREAD

**Issue by juouyCLE** [controllab/fmi-export-20sim#23]
Hello,
since installation of version 4.6.2 I have an error during FMU compilation: 
xxfuncs.obj : error LNK2001: unresolved external symbol xx_stop_simulation

**Comment by margro** [comment]
Thanks for reporting this. It is broken since we added multiple-instance support for FMI.

For now, remove the stopsimulation() calls in your 20-sim model and export again.
In the meantime, we will discuss internally if we should/can support stopsimulation in a co-simulation environment.

I cannot easily fix this without breaking multiple instance support again...
This needs some re-thinking from our side.

**Comment by juouyCLE** [comment]
thanks for the solution

julien
