### ISSUE TITLE
Boolean scalar variables cannot be continuous

### ISSUE THREAD

**Issue by lausdahl** [controllab/fmi-export-20sim#4]
If I export the cascading watertank from DESTECS (with the two tanks imploded) then the exporter creates these scalar variables for the tank1:

``` xml
<ScalarVariable name="valve1.Valve.leakage" valueReference="17" variability="continuous" causality="local">
<Boolean />
</ScalarVariable>

<ScalarVariable name="valve1.leakage" valueReference="17" variability="continuous" causality="local">
<Boolean />
</ScalarVariable>

<ScalarVariable name="leakage" valueReference="21" variability="continuous" causality="input">
<Boolean start="false" />
</ScalarVariable>
```

Output form the COE: 

```
Failed to load and parse model defintion in: src/test/resources/complete-models/cascading/cascadingwatertank1 Reason:  Invalid configuration of scalar variables: 
valve1.Valve.leakage Error: For a continuous variable the type has to be Real
valve1.leakage Error: For a continuous variable the type has to be Real
leakage Error: For a continuous variable the type has to be Real
```

However this is not valid according to the FMI standard version 2. It could look like this depending on what the meaning of the variables in the model is:

``` xml
<ScalarVariable name="valve1.Valve.leakage" valueReference="17" variability="discrete" causality="local">
<Boolean />
</ScalarVariable>

<ScalarVariable name="valve1.leakage" valueReference="17" variability="discrete" causality="local">
<Boolean />
</ScalarVariable>

<ScalarVariable name="leakage" valueReference="21" variability="discrete" causality="input">
<Boolean start="false" />
</ScalarVariable>
```

**Comment by margro** [comment]
I agree that it is not valid according to the standard (FMI 2.0 page 47) so we will fix it.

However, it seems that the standard contains a weird reasoning here. For variability, they refer to the _the time instants when a variable can change its value_. This is referring to the time axis. Discrete means _constant between external and internal events_. Our 20-sim booleans can be part of a continuous system and can therefore change their value at any time instant.
So, if we export a discrete system, we can put it on variability="discrete", but for a continuous system we might need to change the type to a "Real" since the standard somehow does not allow continuous booleans.

It really seems that they mixed up the meaning of _discrete in time_ and _discrete in value_. I would say that this is a bug in the standard...

**Comment by lausdahl** [comment]
I think the whole `variability` is something added for _model exchange_ because the only two options that exists for co-simulation is:
- `discrete`: The meaning of this in a co-simulation context is that it does not have a derivative. 
- `continuous`: This means that it may have a derivative.

Other than the above the co-simulation algorithm does not care about what it is. The co-simulation only has the communication points at where both types of variability has to be present.

So maybe you are right but it will only have an effect in a _model exchange_ context.

I also have trouble understanding the \* "real" samples system\* hint they make since they do not describe what that is.
